language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install libqt4-dev
  - pip install PySide --no-index --find-links https://parkin.github.io/python-wheelhouse/;
  # Travis CI servers use virtualenvs, so we need to finish the install by the following
  - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install # command to run tests
  - pip install -r test_requirements.txt
  - pip install .

script: py.test -q tests/tests.py