language: python
python:
  - "2.7"
# command to install dependencies
install:
  - sudo apt-get install python-pyside
  - pip install -r test_requirements.txt
# command to run tests
script: py.test -q tests/tests.py